---
nameOverride: ""
fullnameOverride: ""

# How to connect to your Synology Diskstation?
connections:
  - host: 192.168.1.1   # the IP V4 address of the Diskstation
    port: 5000          # the port for connecting to the Diskstation Manager application
    https: false        # whether the port expects HTTPS or not
    username: username
    password: password

images:
  attacher:
    image: k8s.gcr.io/sig-storage/csi-attacher
    imagePullPolicy: IfNotPresent
    # tag: v4.2.0
    tag: v4.3.0
  nodeDriverRegistrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    imagePullPolicy: IfNotPresent
    # tag: v2.6.3
    tag: v2.8.0
  plugin:
    image: synology/synology-csi
    pullPolicy: IfNotPresent
    # Defaults to {{ $.Chart.AppVersion }} if empty or not present:
    tag: ""
  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner
    imagePullPolicy: IfNotPresent
    # tag: v3.4.0
    tag: v3.5.0
  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer
    imagePullPolicy: IfNotPresent
    # tag: v1.7.0
    tag: v1.8.0
  snapshotter:
    image: k8s.gcr.io/sig-storage/csi-snapshotter
    imagePullPolicy: IfNotPresent
    # tag: v6.2.1
    tag: v6.2.2
installCSIDriver: true
# Specifies affinity, nodeSelector and tolerations for the node DaemonSet
node:
  affinity: { }
  nodeSelector: { }
  tolerations: [ ]
# Specifies affinity, nodeSelector and tolerations for the snapshotter StatefulSet
snapshotter:
  affinity: { }
  nodeSelector: { }
  tolerations: [ ]

storageClasses:
  delete:
    # One of true or false (default):
    ##disabled: false
    ## One of true or false (default):
    #isDefault: false
    ## One of "Retain" or "Delete" (default):
    reclaimPolicy: Delete
    ## One of "WaitForFirstConsumer" or "Immediate" (default):
    #volumeBindingMode: Immediate

    ## If not present, some location will be chosen to create volumes with the filesystem type ext4.
    ## Note that these parameters cannot get updated once deployed - any subsequent changes get ignored!
    #parameters:
    #  dsm: "1.1.1.1"
    #  fsType: ext4
    #  location: /volume1
  retain:
    reclaimPolicy: Retain

volumeSnapshotClasses:
  delete: { }
    ## One of "Retain" or "Delete" (default):
    #deletionPolicy: Delete
    ## One of true or false (default):
    #isDefault: false

    ## Note that these parameters cannot get updated once deployed - any subsequent changes get ignored!
    #parameters:
    #  description: "Kubernetes CSI"
    #  is_locked: "false"
  retain:
    deletionPolicy: Retain
